name: power_gruas
description: "Aplicación para la gestión de servicios de grúas y asistencia vial."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

  # State Management (Riverpod)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.5

  # Networking
  http: ^1.2.1

  # Navigation
  go_router: ^14.0.2

  # Maps & Location
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0

  # Utilities
  image_picker: ^1.1.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0 # <--- ¡¡¡ AÑADIDO: Necesario para las anotaciones JSON !!!
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Herramientas para generación de código
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  custom_lint:
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_icono_color.png"
  adaptive_icon_background: "#263687"
  adaptive_icon_foreground: "assets/images/logo_blanco_sin_fondo.png"

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-VariableFont_wght.ttf
        - asset: assets/fonts/Arimo-Italic-VariableFont_wght.ttf
          style: italic