// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///    options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3641QfoTo7UxWQwAs8kzNbpzuPPO_z9o',
    appId: '1:661365099508:web:9aae4f5a985933ee4847a1',
    messagingSenderId: '661365099508',
    projectId: 'powergruas-58018',
    authDomain: 'powergruas-58018.firebaseapp.com',
    storageBucket: 'powergruas-58018.firebasestorage.app',
    measurementId: 'G-P48MFELWLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2BDAqMB6EX-qzJz4qDeAFg33gXE-bnDg',
    appId: '1:661365099508:android:cf1d7eebb60196c04847a1',
    messagingSenderId: '661365099508',
    projectId: 'powergruas-58018',
    storageBucket: 'powergruas-58018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLCV9fdmadPkdBuqZCCRLsfJ30bmH0nLo',
    appId: '1:661365099508:ios:2f7b43ea733388444847a1',
    messagingSenderId: '661365099508',
    projectId: 'powergruas-58018',
    storageBucket: 'powergruas-58018.firebasestorage.app',
    iosBundleId: 'com.example.powerGruas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLCV9fdmadPkdBuqZCCRLsfJ30bmH0nLo',
    appId: '1:661365099508:ios:2f7b43ea733388444847a1',
    messagingSenderId: '661365099508',
    projectId: 'powergruas-58018',
    storageBucket: 'powergruas-58018.firebasestorage.app',
    iosBundleId: 'com.example.powerGruas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3641QfoTo7UxWQwAs8kzNbpzuPPO_z9o',
    appId: '1:661365099508:web:0b53e49ef1a5781c4847a1',
    messagingSenderId: '661365099508',
    projectId: 'powergruas-58018',
    authDomain: 'powergruas-58018.firebaseapp.com',
    storageBucket: 'powergruas-58018.firebasestorage.app',
    measurementId: 'G-JYB1JFF56N',
  );
}